name: Build and Test (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup VCPKG
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        cd ..
        ./vcpkg/vcpkg install

    - name: Configure CMake
      run: |
        echo "Current working directory: $(pwd)"
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        # Use the same configuration as the build (Release) so CTest can locate the test binaries
        ctest -C Release --output-on-failure --verbose
